### PR TITLE
Increase delay for lounge music startup

### PR DESCRIPTION
**Pull request by madwort**
* 0.1sec is not long enough on `noiseaa3`

### CODE REVIEW

**Review by sandreae — DISMISSED** [review]
Looks good ;-p

**Comment by madwort** [comment]
plz test!

**Comment by sandreae** [comment]
Working for me right now :+1:

**Comment by sandreae** [comment]
Actually, I found it still wasn't always starting with 0.5 second delay, I increased it locally to 1 second and that seemed to help. See what you think too though.

**Comment by sandreae** [comment]
(not the best track to be testing with, seeing as it starts with a slow fade in from silence ;-p)

**Comment by madwort** [comment]
probably better set conservatively - will amend to 1sec

**Comment by madwort** [comment]
@sandreae could you accept your access to this repo & then do a PR review to approve it at 1sec?

**Pull request merged**
